# dbt_project/dbt_project.yml
# Defines your dbt project configuration.

name: 'sf_fire_analysis'
version: '1.0.0'
config-version: 2

profile: 'sf_fire_profile'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sf_fire_analysis:
    +materialized: table
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'hourly']
    marts:
      +materialized: table
      +schema: analytics
      +tags: ['reporting', 'daily']
