# dbt_project/dbt_project.yml
# Defines your dbt project configuration.

name: 'sf_fire_analysis'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sf_fire_profile' # Matches the profile name in profiles.yml

# These configurations specify where dbt should look for different types of files.
# Relative paths are built from the dbt_project.yml, instead of your CWD
model-paths: ["models"] # Where your SQL models are
analysis-paths: ["analysis"] # Where your SQL analyses (reports) are
test-paths: ["tests"] # Where your custom tests are
seed-paths: ["seeds"] # Where your CSV seed files are (if any)
macro-paths: ["macros"] # Where your macros are
snapshot-paths: ["snapshots"] # Where your snapshots are

# Tells dbt which directories to clean (remove) when running `dbt clean`
clean-targets:
  - "target" # dbt compilation target directory
  - "dbt_packages" # Installed dbt packages

# Configuring models specific to this project
# Apply configurations to all models in the project/subdirectories
models:
  sf_fire_analysis: # Project name
    # Config indicated in +materialized can be overridden in model files
    +materialized: table # Default materialization to tables for marts
    staging:
      +materialized: view # Materialize staging models as views for efficiency
      +schema: staging # Schema for staging models
      +tags: ['staging', 'hourly']
    marts:
      +materialized: table # Materialize marts as tables
      +schema: analytics # Schema for final analytics models (can be overridden by DBT_TARGET_SCHEMA env var)
      +tags: ['reporting', 'daily']

# You can add seeds, tests, snapshots configurations here as well
# seeds:
#   +quote_columns: false

# tests:
#   +severity: warn # Default severity for tests
