# dbt_project/models/sources.yml
# Defines the raw source tables ingested by the ETL process.

version: 2

sources:
  - name: sf_fire_raw # Arbitrary source name
    description: "Raw fire incident data ingested from the Socrata API."
    database: "{{ env_var('DB_NAME') }}" # Or use target.database
    # The schema where the raw table resides is often 'public' by default,
    # or you might configure the ETL to load into a specific 'raw' schema.
    # Adjust if your ETL loads elsewhere. Let's assume 'public' for now.
    schema: public
    # Specify freshness checks if desired (how often source data should be updated)
    # freshness:
    #   warn_after: {count: 12, period: hour}
    #   error_after: {count: 24, period: hour}
    # loaded_at_field: "etl_load_timestamp" # If your ETL adds a load timestamp column

    tables:
      - name: "{{ env_var('STAGING_TABLE_NAME') }}" # Use env var for table name
        description: "Raw staging table containing fire incidents data loaded by Python ETL."
        identifier: "{{ env_var('STAGING_TABLE_NAME') }}" # Explicitly state identifier if needed
        # Define columns for documentation and potential source tests
        columns:
          - name: incident_number
            description: "Unique identifier for the fire incident."
            tests:
              - unique
              - not_null
          - name: response_timestamp
            description: "Timestamp when the response was recorded."
          - name: incident_date
            description: "Date of the incident."
          - name: battalion
            description: "Fire battalion code (e.g., B01)."
          - name: neighborhood_district
            description: "Neighborhood district name."
          - name: analysis_neighborhood
            description: "Analysis neighborhood name."
          # Add other important columns here for documentation
          - name: estimated_property_loss
            description: "Estimated property loss in dollars."
          - name: estimated_contents_loss
            description: "Estimated contents loss in dollars."
          - name: fire_fatalities
            description: "Number of fire fatalities."
          - name: fire_injuries
            description: "Number of fire injuries."

