# dbt_project/models/marts/schema.yml
# Defines tests and descriptions for final data mart models.

version: 2

models:
  - name: dim_battalion
    description: "Dimension table for fire battalions. Contains unique battalion codes and surrogate keys."
    columns:
      - name: battalion_key
        description: "Surrogate key for the battalion."
        tests:
          - unique
          - not_null
      - name: battalion_code
        description: "The unique code identifying the fire battalion (e.g., B01)."
        tests:
          - unique # Natural key should also be unique
          - not_null

  - name: dim_neighborhood_district
    description: "Dimension table for neighborhood districts."
    columns:
      - name: neighborhood_district_key
        description: "Surrogate key for the neighborhood district."
        tests:
          - unique
          - not_null
      - name: neighborhood_district
        description: "The name of the neighborhood district."
        tests:
          - unique
          - not_null

  - name: dim_time
    description: "Time dimension table containing date attributes, generated from incident dates."
    columns:
      - name: time_key
        description: "Surrogate key for the date."
        tests:
          - unique
          - not_null
      - name: calendar_date
        description: "The specific date."
        tests:
          - unique
          - not_null

  - name: fct_incidents
    description: "Fact table containing fire incident records, linking to dimension tables. Granularity: one row per incident exposure."
    tests:
      # Example relationship tests: ensure foreign keys exist in dimension tables
      - dbt_utils.relationships:
          to: ref('dim_time')
          field: time_key
          # Specify severity: error or warn
          config:
            severity: warn # Warn if a time_key doesn't exist (might happen for bad data)
      - dbt_utils.relationships:
          to: ref('dim_battalion')
          field: battalion_key
          config:
            severity: warn
      - dbt_utils.relationships:
          to: ref('dim_neighborhood_district')
          field: neighborhood_district_key
          config:
            severity: warn

    columns:
      # Foreign Keys
      - name: time_key
        description: "Foreign key linking to the dim_time table."
        tests:
          - not_null # Fact should always link to a time dimension row
      - name: battalion_key
        description: "Foreign key linking to the dim_battalion table."
        tests:
          - not_null
      - name: neighborhood_district_key
        description: "Foreign key linking to the dim_neighborhood_district table."
        tests:
          - not_null

      # Degenerate Dimensions
      - name: incident_number
        description: "The original incident number."
        tests:
          - not_null
      - name: exposure_number
        description: "The original exposure number for the incident."
        tests:
          - not_null

      # Measures
      - name: estimated_property_loss
        description: "Estimated property loss in dollars."
      - name: estimated_contents_loss
        description: "Estimated contents loss in dollars."
      - name: fire_fatalities
        description: "Number of fire fatalities."
      - name: fire_injuries
        description: "Number of fire injuries."

      # Add descriptions for other measures and attributes

analyses:
  - name: incident_aggregations_report
    description: "Aggregated report of fire incidents grouped by time periods, battalion, and neighborhood district. Shows counts, losses, fatalities, injuries, and average personnel."
    columns:
      - name: year
        description: "The calendar year of the incidents."
      - name: year_month
        description: "The year and month (YYYY-MM format) of the incidents."
      - name: month_name
        description: "The full name of the month (e.g., January)."
      - name: battalion_code
        description: "The code identifying the fire battalion."
      - name: neighborhood_district
        description: "The name of the neighborhood district."
      - name: total_incidents
        description: "The total count of incidents for the group."
      - name: total_alarms
        description: "The sum of the number of alarms for incidents in the group."
      - name: total_estimated_loss
        description: "The sum of estimated property and contents loss for incidents in the group."
      - name: total_fire_fatalities
        description: "The total count of fire-related fatalities for incidents in the group."
      - name: total_fire_injuries
        description: "The total count of fire-related injuries for incidents in the group."
      - name: total_civilian_fatalities
        description: "The total count of civilian fatalities for incidents in the group."
      - name: total_civilian_injuries
        description: "The total count of civilian injuries for incidents in the group."
      - name: avg_suppression_personnel
        description: "The average number of suppression personnel responding to incidents in the group."
      - name: avg_ems_personnel
        description: "The average number of EMS personnel responding to incidents in the group."
